server {
	listen 127.0.0.1/8080;
	
	server_name webserv;
	
	client_max_body_size 80;
	
	location /some/path/ {
		root /src;
		limit_except GET, POST, DELETE;
		autoindex on;
		index index.html;
		upload_store /upload;
	}
}