server {
	listen 127.0.0.1/8080;
	listen 0.0.0.0/9090;

	server_name webserv;

	error_page 405 errors/405.html;

	client_max_body_size 80000000;

	cgi_max_output_size 20000000;

	root /data/www/blue/pages;

    location / {
        root /data/www/blue/pages;
        limit_except GET, POST;
        autoindex on;
        index index.html;
        upload_store /data/upload;
    }

    location /upload {
        root /data;
        upload_store /data;
    }

    location /files {
        root /data/www/blue;
        return 301 http://127.0.0.1:9090/cgi-bin/oldlistfiles.py;
    }

    location /assets {
        root /data/www/blue;
        autoindex on;
    }

    location /css {
        root /data/www/blue;
        autoindex off;
        error_page 403 pages/errors/403.html;
    }

	location /cgi-bin {
        root /data/www/blue;
        autoindex on;
    }

	location /www/pages/ {
		root /data/www/pages/blue;
		limit_except GET, POST, DELETE;
		autoindex on;
		index index.html;
		upload_store /upload;
		error_page 404 pages/errors/404.html;
	}

    location /redir.html {
        root /data/www/pages/blue;
        return 301 https://www.youtube.com;
    }
}
