server {
	listen 127.0.0.1/8080;
	listen 127.0.0.1/9090;
	
	server_name webserv;

	error_page 405 /405.html;
	
	client_max_body_size 80000000;

	root /www;
    index /index.html;

    location / {
        root /www/pages;
        autoindex on;
        index /index.html;
    }

    location /assets {
        root /www;
        autoindex on;
    }

    location /css {
        root /www;
        autoindex on;
    }

	location /www/pages/{
		root /www/pages;
		limit_except GET, POST, DELETE;
		autoindex on;
		index index.html;
		upload_store /upload;
		error_page 404 /404.html;
		return 301 www.redirect.com;
	}
}